### ISSUE TITLE
Note Python extensions needed

### ISSUE THREAD

**Issue by bmschmidt** [Bookworm-project/Docs#2]
## Peter Leonard notes the following addition needed to the docs. 

on this page:

http://bookworm-project.github.io/Docs/Building.html

...at least on homebrew-provided python 2.7 -- Mac users will need to install via pip:

MySQL-python
python-dateutil

**Comment by organisciak** [comment]
I put up a [Gist of a clean install on Amazon Linux](https://gist.github.com/e240d7b63dfcce933ba0), this might give you some other ideas for that page. e.g.

```
yum groupinstall -y "Web Server" "MySQL Database" "PHP Support"
yum install -y php-mysql mysql mysql-devel python-devel
...
sudo pip install regex virtualenv nltk numpy pandas mysql-python
```

**Comment by bmschmidt** [comment]
`parallel` is also needed on some systems as an unpackaged dependency through `yum` or `apt-get`.

EDIT: Oh I see you've already got it there, it's just not a yum package, I guess?

**Comment by bmschmidt** [comment]
Closing this issue: now that the recommended form of installation is 'pip install .', the proper dependencies are pulled straight out the `setup.py` file.
